Exercise 7
Systems-Development-and-Frameworks/abteilung6 pull request #10
Opened 2021-01-06 17:37 UTC by steven-mi

Pull Request for changing to nuxt.js: https://github.com/Systems-Development-and-Frameworks/abteilung6/pull/9#issue-550501741

Review for the other team:

2021-01-08 23:05 UTC, steven-mi commented
@Systems-Development-and-Frameworks/mentors if possible, could you perhaps assess if everything is ok? Everything except the tests should be done. 

I was also not sure if it is necessary to implement delete and downvote. Could this perhaps be clarified?

2021-01-26 14:55 UTC, s0557917 requested changes
⭐ ⭐ For the API connection between your front- and backend.
⭐ For no changes in "Files Changed" tab of the refactoring from vue-cli to create-nuxt-app

2021-01-26 14:55 UTC, s0557917 commented on webapp/README.md
> -# hackernews
⭐ For instructions in the README.md on how to build your webapp for production.

2021-01-26 14:55 UTC, s0557917 commented on webapp/components/LoginForm/LoginForm.spec.js
> +import { mount } from '@vue/test-utils'
⭐ ⭐ For a login feature in your webapp including a Vue component and its software tests.

2021-01-26 14:55 UTC, s0557917 commented on webapp/components/List/List.vue
> +      :is-authenticated="isAuthenticated"
⭐ For a delete button that is only visible to the author of the post.
❌ I was not able to find your edit button, did you implement it? Or did I oversee it?

2021-01-26 14:55 UTC, s0557917 commented on webapp/components/Navbar/Navbar.spec.js
> +    expect(wrapper.text()).toContain('Login')
⭐ ⭐ For a menu component which shows a login or logout button and its software tests.

2021-01-26 14:55 UTC, s0557917 commented on webapp/components/ListItem/ListItem.vue
> +    <button v-if="isAuthenticated" @click="upvoteItem()">Upvote</button>
⭐ For an upvote button that behaves according to the authentication state of your user

2021-01-27 08:59 UTC, Aimtracker approved these changes
I do like your concise coding style which makes it easy to read and navigate through your code. The only thing I did find was that the edit button is apparently missing, but maybe I just didn't find that? Otherwise great work!

2021-01-27 08:59 UTC, Aimtracker commented on webapp/README.md
> +## Deploy static project
⭐ For instructions in the README.md on how to build your webapp for production.

2021-01-27 08:59 UTC, Aimtracker commented on webapp/components/LoginForm/LoginForm.vue
> +  name: 'LoginForm',
⭐ ⭐ For a login feature in your webapp including a Vue component and its software tests.

2021-01-27 08:59 UTC, Aimtracker commented on webapp/components/Navbar/Navbar.vue
> +  name: 'Navbar',
⭐ ⭐ For a menu component which shows a login or logout button and its software tests.

2021-01-27 08:59 UTC, Aimtracker commented on webapp/components/ListItem/ListItem.vue
> +    <button v-if="isAuthenticated" @click="upvoteItem()">Upvote</button>
⭐ For an upvote button that behaves according to the authentication state of your user

2021-01-27 08:59 UTC, Aimtracker commented on webapp/components/ListItem/ListItem.vue
> +    <button v-if="item.isOwner" @click="$emit('delete-item', item)">
⭐ For a delete and edit button that is only visible to the author of the post.

Note: I did not find an edit button.

2021-01-27 12:53 UTC, merged

2021-02-03 22:11 UTC, medizinmensch reviewed
Hi @abteilung6!

Thanks for the PR. 

I can entirely agree with @Aimtracker  and @s0557917 . Both noted correctly that you're missing an edit button. As it's written in the description, connection to the backend is optional. So a dummy button would have been okay. Pity!
❌    For a delete and edit button that is only visible to the author of the post.

But it looks good apart from that:

⭐ For instructions in the   README.md on how to build your webapp for production.
⭐ For   no changes in "Files Changed" tab of the refactoring from vue-cli   to create-nuxt-app. (See #1 in instructions)
⭐ ⭐ For the API connection   between your front- and backend.
⭐ For   your previous frontend tests still passing. Requests to the backend are   mocked.
⭐ ⭐ For a login feature in your   webapp including a Vue component and its software tests.
⭐ ⭐ For   a menu component which shows a login or logout button and its software tests.
⭐ For an upvote button that   behaves according to the authentication state of your user
⭐ For Lighthouse reporting that   your production website is installable as PWA (except HTTPS).
⭐ For   requesting a review and reviewing another team's PR.

But apart from that, quite nice! You could have tried to keep the PR a bit smaller. Keep that in mind for the future. 

12/13 ⭐ 

![](https://media2.giphy.com/media/ftdTlqaGUEJ0Gitzxe/giphy.gif)


Thanks!